### ISSUE TITLE
Usability: Links are not linked with appropriate resource

### ISSUE THREAD

**Issue by janiereyna** [edwinsoto88/color-vision#14]
![image](https://user-images.githubusercontent.com/102683660/198928675-bf367c70-688b-4bb4-b074-49d7a9919535.png)

**Comment by edwinsoto88** [comment]
Issue resolved during sprint 5, links are now working with appropriate resources
<img width="556" alt="Screenshot 2022-11-28 at 12 43 08 PM" src="https://user-images.githubusercontent.com/61428070/204355667-da023858-058c-4cbb-9776-ff6d7c3df4d0.png">
