### ISSUE TITLE
Home Page Background Not Loading Properly

### ISSUE THREAD

**Issue by beion2000** [edwinsoto88/color-vision#3]
When loading the home page, the background image is not present and the text in the navigation menu is not visible.

<img width="1402" alt="Screen Shot 2022-10-28 at 10 01 08 AM" src="https://user-images.githubusercontent.com/113634265/198665186-1d58dd46-9a3c-44ae-8ad8-48b778679da5.png">

**Comment by edwinsoto88** [comment]
This issue has been resolved as the background image displays to the user
